### ISSUE TITLE
the code part

### ISSUE THREAD

**Issue by SoonyangZhang** [alibaba-edu/High-Precision-Congestion-Control#1]
I am a bit curious about where is the code implementation of Algorithm1 describted in the paper? It seems not in RdmaClient.

**Comment by bukatea** [comment]
@SoonyangZhang I know I'm about a year late, but try `src/point-to-point/model/rdma-hw.cc`. Around like line 715 you'll the function that corresponds to "procedure NEWACK(ack)" in Algorithm 1.
