### ISSUE TITLE
Version 

### ISSUE THREAD

**Issue by Alan-Ou** [alibaba-edu/High-Precision-Congestion-Control#10]
My system version may be inconsistent with the system version required by hpcc's ns3 code, which makes it very troublesome to solve many software version dependencies, so I want to solve this problem through docker. Can you tell me the ubuntu version, ns3 version and corresponding dependencies used in the development process?

**Comment by duanjunshang** [comment]
The ubuntu I used is Ubuntu 16, ns3 3.17. I don't remember all the dependencies, sorry.

But I think in general if you have gcc-5 & g++-5, it should work

**Comment by liyuliang001** [comment]
I used Ubuntu 16, ns-3.17. Sorry I don't remember the dependencies. But there are not many dependencies, and should be mostly easy to fix

**Comment by Alan-Ou** [comment]
Thanks a lot, I will try it
