### ISSUE TITLE
Does HPCC require per-packet ACK? 

### ISSUE THREAD

**Issue by Yi-ran** [alibaba-edu/High-Precision-Congestion-Control#12]
Hi, I have a small question. HPCC needs ACK to piggyback INT information, and I also notice that the L2_ACK_INTERVAL is set to 1 in the config.txt. Does it mean that HPCC NICs need support per-packet ACK? Or it can also tolerate if ACK is not per-packet?
Thank you.

**Comment by liyuliang001** [comment]
Hi Yiran, 

Run without per-packet ACK is ok for HPCC. You may see [PINT [sigcomm 2020]](https://liyuliang001.github.io/publications/pint.pdf) Figure 8 to see how HPCC performs under 1 ACK every 16 packets.
