### ISSUE TITLE
Compile failed

### ISSUE THREAD

**Issue by liulalala** [alibaba-edu/High-Precision-Congestion-Control#2]
Dr.miao, 
            I have some problem compiling the source code of HPCC. The error information is as below,

![1](https://user-images.githubusercontent.com/23302557/67484219-2e147580-f69a-11e9-8eb2-2daefac3d1dd.png)

My gcc version is 5.4.0.
Looking forward to your reply! Thanks a lot!

**Comment by MO9096** [comment]
Hi ,
actually me too a have the same problem and my gcc version 5.5.0. 
![image](https://user-images.githubusercontent.com/55055329/67747273-54079480-fa63-11e9-90f8-6df4e4a5d212.png)

**Comment by liyuliang001** [comment]
Please just remove the `include <ns3/broadcom-node.> ` from node.h

**Comment by MO9096** [comment]
After removing the include <ns3/broadcom-node.h> from node.h , still have the same problem . Did it work with you ? and maybe can you help me with another suggestion please

**Comment by liyuliang001** [comment]
> After removing the include <ns3/broadcom-node.h> from node.h , still have the same problem . Did it work with you ? and maybe can you help me with another suggestion please

What error are you getting now?

**Comment by Kwangwook-Kwon** [comment]
I fixed below solutions.

#1. copy broadcom-node.h files from window folder to src/network

 >> cp ./windows/ns-3-dev/headers/ns3/broadcom-node.h ./src/network/model/broadcom-node.h

#2. insert broadcom-node.h to wscript

 >> vi ./src/network/wscript
![image](https://user-images.githubusercontent.com/35948244/68607216-6ff34780-04f3-11ea-8f99-7c7d568b2983.png)

**Comment by MO9096** [comment]
> I fixed by below solution.
> 
> #1. copy broadcom-node.h files from window folder to src/network
> 
> > > cp ./windows/ns-3-dev/headers/ns3/broadcom-node.h ./src/network/model/broadcom-node.h
> 
> #2. insert broadcom-node.h to wscript
> 
> > > vi ./src/network/wscript
> > > ![image](https://user-images.githubusercontent.com/35948244/68607216-6ff34780-04f3-11ea-8f99-7c7d568b2983.png)

It's working with your solution . 
Thank you

**Comment by MO9096** [comment]
i tried to Plot graphs using TraceMetrics for this file (mix_topology_flow_hp95ai50.tr) after implementing the HPCC code , but it doesn't work , is it because the file size is too big ? any other ideas may help please 
![image](https://user-images.githubusercontent.com/55055329/69035308-4fa91880-0a1e-11ea-89f4-e0afaf73aea6.png)

**Comment by MO9096** [comment]
Hi ,
How to read and analyse the output trace file?

**Comment by Annier49** [comment]
> Hi ,
> How to read and analyse the output trace file?

Hi，I opened the trace output file and it was garbled. Do you have the same problem?

**Comment by liyuliang001** [comment]
The compilation error is fixed.

**Comment by liyuliang001** [comment]
> > Hi ,
> > How to read and analyse the output trace file?
> 
> Hi，I opened the trace output file and it was garbled. Do you have the same problem?

Added a trace_reader. Please refer to #5.
