### ISSUE TITLE
Can I run the simulator only with PFC and without any CC algorithm? 

### ISSUE THREAD

**Issue by songhexiang** [alibaba-edu/High-Precision-Congestion-Control#26]
Hi yuliang, Can I run the the simulator only enable the PFC and without any CC algorithm? 
In addition, How to disable the PFC?
thx

**Comment by liyuliang001** [comment]
You can implement a dumb CC in
https://github.com/alibaba-edu/High-Precision-Congestion-Control/blob/master/simulation/src/point-to-point/model/rdma-hw.cc#L434, by implementing a HandleAckDumb() as an empty function.

**Comment by songhexiang** [comment]
When I compile the trace_reader, I encounter this problem
![image](https://user-images.githubusercontent.com/25613681/127629059-7173d517-1fdf-462a-b949-8f30a085521c.png)

thx
