### ISSUE TITLE
compile error (trace_reader)

### ISSUE THREAD

**Issue by songhexiang** [alibaba-edu/High-Precision-Congestion-Control#27]
Hi yuliang, I have compiled the ns-3 simulator, but when I compiled the trace_reader, I encountered the problem.
![image](https://user-images.githubusercontent.com/25613681/127793673-9d8df48a-e0c9-4395-9736-0c7bc2820704.png)
The version of gcc and g++ is 5.3.0

**Comment by dongzhiydz** [comment]
Hi，master，I met the same problem as you. How did you solve it? thanks
![image](https://user-images.githubusercontent.com/60928893/167979348-cecf1266-64d2-49b1-b4f4-1bd07aeee5f4.png)

**Comment by jxzhuge** [comment]
> 嗨，主人，我遇到了和您一样的问题。您是怎么解决的？谢谢 ![image](https://user-images.githubusercontent.com/60928893/167979348-cecf1266-64d2-49b1-b4f4-1bd07aeee5f4.png)

您好，我和您遇到了一样的问题，请问您解决了吗？谢谢
