### ISSUE TITLE
Question on PACKET_PAYLOAD_SIZE in config

### ISSUE THREAD

**Issue by fufjvnvnf** [alibaba-edu/High-Precision-Congestion-Control#3]
Hi all.

According to  config_doc.txt the PACKET_PAYLOAD_SIZE is in KB. 

When I looked at CalculateRoute in scratch/third.cc, packet_payload_size is multiplied by 8, which seems to suggest that packet_payload_size is in bytes. 

Could you please confirm if this is the case? Thank you!

**Comment by liyuliang001** [comment]
You are right. It is in Bytes. Sorry for the confusion. Will fix it soon.

**Comment by liyuliang001** [comment]
I have fixed it.
