### ISSUE TITLE
fct and pfc file is empty

### ISSUE THREAD

**Issue by huangjiawe** [alibaba-edu/High-Precision-Congestion-Control#31]
老师你好，不好意思，用了中文向您提问，因为学生英文水平有限，怕不能用英文 讲清楚我的问题。
我的问题如下
在复现您的实验也就是论文中的图11（a）和（c）。我用生成的30%负载的fbhdp流量和fat tree网络架构和dcqcn算法，仿真后得到的fct和pfc文件都是空的。不知道是哪里出错了，还请老师能解答，非常感谢。

**Comment by dongzhiydz** [comment]
我得到的pfc文件也是空的，但是fct文件不是空的。想请问一下如何分析tr文件呢

**Comment by dongzhiydz** [comment]
我输入 make trace_reader
出现如下提示：make: *** No rule to make target 'trace_reader'。 停止。
![image](https://user-images.githubusercontent.com/60928893/167814403-b2dcc56f-86cd-478b-8d1d-7b8f27cfae4d.png)

**Comment by liyuliang001** [comment]
Please do the `make trace_reader` under analysis/
