### ISSUE TITLE
Hi,Mr. Miao: I generated a .tr file using the EnableTracing () function file of the QbbNetDevice class, but I garbled it after opening it with NotePad ++, and I tried many ways and there was no way to solve it. How do I open it to prevent garbled?

### ISSUE THREAD

**Issue by Annier49** [alibaba-edu/High-Precision-Congestion-Control#5]

**Comment by Annier49** [comment]
And I tried to use the EnableAsciiAll () function to output the queue information, but it can only output the received information.

**Comment by liyuliang001** [comment]
Hi, I will try to upload the trace reader soon.

**Comment by liyuliang001** [comment]
Hi, Please check trace reader in https://github.com/alibaba-edu/High-Precision-Congestion-Control/tree/master/analysis#trace-reader.
