### ISSUE TITLE
Compilation failing with error: passing ‘const ns3::CommandLine’ as ‘this’ argument discards qualifiers

### ISSUE THREAD

**Issue by bukatea** [alibaba-edu/High-Precision-Congestion-Control#6]
Hello,
I'm attempting to compile HPCC on an Ubuntu 16.04 LTS machine, and I followed the instructions of #2 in order to get passed the broadcom-node.h error, but after I do that, I'm getting a new error. I'm running gcc/g++ 5.4.0 btw.

<pre>
<code>
[ 756/1761] cxx: src/wimax/test/wimax-fragmentation-test.cc -> build/debug/src/wimax/test/wimax-fragmentation-test.cc.3.o
../../src/core/test/command-line-test-suite.cc: In member function ‘void ns3::CommandLineTestCaseBase::Parse(const ns3::CommandLine&, int, ...)’:
../../src/core/test/command-line-test-suite.cc:64:24: error: passing ‘const ns3::CommandLine’ as ‘this’ argument discards qualifiers [-fpermissive]
   cmd.Parse (argc, args);
                        ^
In file included from ../../src/core/test/command-line-test-suite.cc:20:0:
./ns3/command-line.h:224:8: note:   in call to ‘void ns3::CommandLine::Parse(int, char**)’
   void Parse (int argc, char *argv[]);
        ^
Waf: Leaving directory `/home/jhl56/High-Precision-Congestion-Control/build/debug'
Build failed
 -> task in 'ns3-core-test' failed (exit status 1): 
	{task 140191403070416: cxx command-line-test-suite.cc -> command-line-test-suite.cc.3.o}
['/usr/bin/g++', '-O0', '-ggdb', '-g3', '-std=gnu++11', '-Wno-error=deprecated-declarations', '-fstrict-aliasing', '-Wstrict-aliasing', '-I../../src/core', '-fPIC', '-pthread', '-I.', '-I../..', '-DNS3_ASSERT_ENABLE', '-DNS3_LOG_ENABLE', '-DHAVE_PACKET_H=1', '-DHAVE_IF_TUN_H=1', '-DNS_TEST_SOURCEDIR="src/core/test"', '../../src/core/test/command-line-test-suite.cc', '-c', '-o', 'src/core/test/command-line-test-suite.cc.3.o']
</code>
</pre>

Any help would be greatly appreciated.
Thanks

**Comment by GuShuhengSimon** [comment]
hi Bukatea, have you fixed this problem? I also got this problem, but not in step2.  
when I try to run MPI examples in NS3, it failes. 

[1542/1770] cxx: src/core/examples/main-callback.cc -> build/src/core/examples/main-callback.cc.1.o
../src/core/test/command-line-test-suite.cc: In member function ‘void ns3::CommandLineTestCaseBase::Parse(const ns3::CommandLine&, int, ...)’:
../src/core/test/command-line-test-suite.cc:64:24: error: passing ‘const ns3::CommandLine’ as ‘this’ argument discards qualifiers [-fpermissive]
   cmd.Parse (argc, args);
                        ^
In file included from ../src/core/test/command-line-test-suite.cc:20:0:
./ns3/command-line.h:224:8: note:   in call to ‘void ns3::CommandLine::Parse(int, char**)’
   void Parse (int argc, char *argv[]);
