### ISSUE TITLE
Large Topos?

### ISSUE THREAD

**Issue by ChengjunJia** [alibaba-edu/High-Precision-Congestion-Control#9]
Have you tried extremely large topos? 
I found that Ptr<RdmaHw> rdmaHw = CreateObject<RdmaHw>() or sw->SetAttribute("CcMode", UintegerValue(cc_mode)) in third.cc would fail if the topo is more than 6K nodes.

**Comment by liyuliang001** [comment]
Great question. We haven't tried. Would you mind sharing your topology with us so we can see what happens?

**Comment by ChengjunJia** [comment]
Unfortunately I encountered more questions. Pls find the topo and flows below. This topo consists of 4004 nodes, and it can be created without error, but running with only 1 flow leads to Segmentation fault.

If you notice, the topo is an asymmetric dumbbell topo, increasing the node num on the left side to 5000 or more, creating the topo will fail.

==========topo===========

4004 2 4003
4000 4001
0	4000	100Gbps	3.33us	0
1	4000	100Gbps	3.33us	0
......(node 2-3997, are connected to 4000)
3998	4000	100Gbps	3.33us	0
3999	4000	100Gbps	3.33us	0
4000	4001	100Gbps	3.33us	0
4001	4002	100Gbps	3.33us	0
4001	4003	100Gbps	3.33us	0

==========flow==============
1
0	4002	3	100	2	0.001

**Comment by liyuliang001** [comment]
Thanks for sharing. I tried to create 5000+ nodes and also fails. But I note that it consumes > 9Gb memory before crashes. I think this is an NS3 problem. Have you tried creating 5000+ nodes in raw NS3?

**Comment by ChengjunJia** [comment]
Thanks. I will try.
